services:
  - type: web
    name: smart-investor-nextjs
    env: node
    plan: standard
    region: oregon
    buildCommand: npm run build
    startCommand: npm run start
    build:
      cache:
        - path: /node_modules
        - path: .next/cache
    envVars:
      - key: NODE_ENV
        value: production
    routes:
      - type: manual
        source: /
        destination: /
